### ISSUE TITLE
Add sync events

### ISSUE THREAD

**Issue by Florian-R** [jmorrell/backbone.obscura#21]
Related to jmorrell/backbone-collection-proxy#2

I've missed this when i opened the previous issue, but [Obscura took its events from an internally created collection](https://github.com/jmorrell/backbone.obscura/blob/master/backbone.obscura.js#L344) and not from its superset.

I'd happily open a PR for this, but for now i'm not sure about how to tackle this cleanly.

**Comment by jmorrell** [comment]
Hmm... good point. I think the only way to do this is to make sure the underlying collections (filtered, sorted, paginated) pass on those events. I agree that they should, since there's an obvious use case.

If you want to try, I'm happy to approve PRs on the three libraries. If not, I'll try to get it done in the next couple of days.

**Comment by Florian-R** [comment]
Thanks for your attention. Pretty busy ATM, but i'll try do give it a shot in the middle of the week.

**Comment by Florian-R** [comment]
Had finally some time to shim on this, sorry for the delay.

Curious to know what you'd mean by 

> I think the only way to do this is to make sure the underlying collections

Something like 

``` js
this.listenTo(this._collection, 'sync request error', function () {
  this.trigger.apply(this, arguments)
});
```

in each underlying collection constructor or you had another idea in mind?
